import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,mkdir} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {chromium} from 'playwright-core';
import {createFixture,initScript} from './browser/fixture.mjs';
import {chromeExecutable} from './browser/chrome.mjs';

test('synthetic microphone captures encoded take after countdown, restores draft and saves corrected mix idempotently',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'vgm-mic-test-'));
 const fixture=await createFixture(dir,{flac:true,seconds:12});
 const browser=await chromium.launch({executablePath:chromeExecutable(),headless:true,args:['--mute-audio']});
 try {
  const context=await browser.newContext();await context.addInitScript(initScript);
  await context.addInitScript(()=>{
   window.__micRequests=0;window.__micStops=0;window.__denyMic=true;
   navigator.mediaDevices.getUserMedia=async()=>{
    window.__micRequests++;
    if(window.__denyMic){window.__denyMic=false;throw new DOMException('Microphone permission denied','NotAllowedError');}
    const c=new AudioContext(),osc=c.createOscillator(),out=c.createMediaStreamDestination();
    osc.frequency.value=330;osc.connect(out);osc.start();await c.resume();
    for(const track of out.stream.getTracks()) { const stop=track.stop.bind(track);track.stop=()=>{window.__micStops++;stop();if(c.state!=='closed')void c.close();}; }
    return out.stream;
   };
  });
  await context.route('**/data/catalog.json',async route=>{const response=await route.fetch(),catalog=await response.json();catalog.references=catalog.references.map(ref=>ref.id==='alpha-original'?{...ref,...fixture.referenceAudio}:ref);await route.fulfill({json:catalog});});
  await context.route('https://www.youtube.com/iframe_api',route=>route.fulfill({contentType:'text/javascript',body:fixture.youtubeApi}));
  let ambiguous=true;
  await context.route('**/api/jams',async route=>{if(route.request().method()==='POST'&&ambiguous){ambiguous=false;await route.fetch();await route.fulfill({status:502,json:{error:'Save response interrupted'}});}else await route.continue();});
  const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
  page.on('response',async response=>{if(response.url().endsWith('/api/jams')&&response.status()>=400)console.log('Synthetic jam response',response.status(),await response.text());});
  await page.goto(fixture.origin+'/?view=songs&song=synthetic-alpha');
  const panel=page.getByRole('region',{name:'Record a jam'});
  await panel.getByRole('button',{name:'Jam recording',exact:true}).click();
  await page.waitForFunction(()=>!document.querySelector('.jam-recorder button:last-of-type')?.disabled);
  assert.equal(await page.evaluate(()=>window.__micRequests),0);
  await panel.getByRole('textbox',{name:'Title',exact:true}).fill('Synthetic mic take');
  await page.getByRole('slider',{name:'Seek full recording'}).evaluate(el=>{const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(el,'2');el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});
  await page.getByRole('button',{name:'Playback speed 1 times; toggle original speed'}).dispatchEvent('wheel',{deltaY:100});
  await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  await page.getByRole('button',{name:'Playback speed 0.9 times; toggle original speed'}).dispatchEvent('wheel',{deltaY:100});
  await page.getByRole('button',{name:'Playback speed 0.8 times; toggle original speed'}).waitFor();
  await panel.getByRole('button',{name:'Enable microphone',exact:true}).click();
  await panel.getByText('Microphone permission denied',{exact:true}).waitFor();
  assert.equal(await page.evaluate(()=>window.__micRequests),1);assert.equal(await panel.getByText('Unsaved draft',{exact:false}).count(),0);
  await panel.getByRole('button',{name:'Enable microphone',exact:true}).click();
  await panel.getByRole('button',{name:'Record after 3 seconds'}).click();
  await panel.getByRole('button',{name:'Cancel countdown',exact:true}).click();
  assert.ok(await page.evaluate(()=>window.__micStops)>0);assert.equal(await panel.getByText('Unsaved draft',{exact:false}).count(),0);
  await panel.getByRole('button',{name:'Enable microphone',exact:true}).click();
  await panel.getByRole('button',{name:'Record after 3 seconds'}).waitFor();
  assert.equal(await page.getByRole('slider',{name:'Seek full recording'}).isDisabled(),true);
  await panel.getByRole('button',{name:'Record after 3 seconds'}).click();
  await panel.getByText('Recording starts in 3…',{exact:true}).waitFor();
  await panel.getByText('Recording microphone',{exact:false}).waitFor();
  await page.waitForFunction(()=>Number(document.querySelector('input[aria-label="Seek full recording"]').value)>3);
  await mkdir('.test-artifacts/jam-capture',{recursive:true});
  await page.screenshot({path:'.test-artifacts/jam-capture/recording-desktop.png'});
  await page.setViewportSize({width:375,height:812});
  await panel.getByRole('button',{name:'Stop',exact:true}).scrollIntoViewIfNeeded();
  assert.equal(await panel.getByRole('button',{name:'Stop',exact:true}).isVisible(),true);
  assert.equal(await page.locator('.workspace-main').evaluate(el=>el.scrollWidth<=el.clientWidth+1),true);
  await page.screenshot({path:'.test-artifacts/jam-capture/recording-phone.png'});
  await page.keyboard.press('Space');
  await panel.getByRole('button',{name:'Save privately',exact:true}).waitFor();
  await page.waitForFunction(()=>!Array.from(document.querySelectorAll('.jam-recorder button')).find(b=>b.textContent==='Save privately')?.disabled);
  assert.ok(await page.evaluate(()=>window.__micStops)>0);
  await panel.getByRole('button',{name:'Earlier',exact:true}).click();
  await panel.getByText('Timing saved in this browser.',{exact:true}).waitFor();
  await page.reload();
  await panel.getByText('Synthetic mic take',{exact:true}).waitFor();
  assert.match(await panel.innerText(),/0.05 s earlier/);
  await panel.getByRole('button',{name:'Save privately',exact:true}).click();
  await panel.getByText('Your draft and retry ID are retained.',{exact:false}).waitFor();
  await panel.getByRole('button',{name:'Save privately',exact:true}).click();
  await panel.getByText('Saved privately. Timing is estimated; adjust it by ear if needed.',{exact:true}).waitFor();
  const jams=await (await page.request.get(fixture.origin+'/api/jams?song=synthetic-alpha')).json();
  assert.equal(jams.jams.length,1);const jam=jams.jams[0];
  assert.equal(jam.alignment.correctionSeconds,.05);assert.ok(jam.alignment.coverage.sourceStart>=1.999);assert.ok(jam.audio.mimeType.includes('webm'));
  assert.equal(jam.backingMix.playbackRate,.8);assert.equal(jam.backingMix.mode,'stems');assert.equal(jam.backingMix.stems.tracks.length,6);
  await panel.getByRole('button',{name:'Play with recorded mix',exact:true}).click();
  await page.waitForFunction(()=>{const audio=document.querySelector('.jam-review audio');return audio&&!audio.paused;});
  assert.equal(await page.getByRole('slider',{name:'Seek full recording'}).isDisabled(),true);
  await page.getByRole('button',{name:'Mute Piano',exact:true}).click();
  await panel.getByRole('button',{name:'Reset recorded mix',exact:true}).click();
  await panel.getByText('Recorded mix restored, paused.',{exact:true}).waitFor();
  assert.equal(await page.getByRole('button',{name:'Mute Piano',exact:true}).getAttribute('aria-pressed'),'false');
  assert.equal(await panel.locator('audio').evaluate(el=>el.paused),true);
  await panel.getByRole('button',{name:'New jam',exact:true}).click();
  await page.evaluate(()=>window.__denyMic=false);
  await page.getByRole('button',{name:'Original mix',exact:true}).click();
  await page.waitForFunction(()=>window.__media.some(audio=>audio.getAttribute('src')&&audio.readyState>=1)&&!document.querySelector('input[aria-label="Seek full recording"]').disabled);
  await page.getByRole('slider',{name:'Seek full recording'}).evaluate(el=>{const set=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set;set.call(el,'3');el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});
  await page.waitForFunction(()=>window.__media.some(audio=>audio.src&&Math.abs(audio.currentTime-3)<.01));
  await panel.getByRole('button',{name:'Enable microphone',exact:true}).click();
  await panel.getByRole('button',{name:'Record after 3 seconds'}).click();
  await panel.getByText('Recording microphone',{exact:false}).waitFor();
  await page.waitForFunction(()=>window.__media.some(audio=>!audio.paused&&audio.currentTime>3.5));
  await page.evaluate(()=>{const audio=window.__media.find(a=>!a.paused);audio.dispatchEvent(new Event('waiting'));audio.dispatchEvent(new Event('playing'));});
  await panel.getByRole('button',{name:'Save privately',exact:true}).waitFor();
  assert.match(await panel.innerText(),/Backing stopped or buffered/);
  await panel.getByRole('button',{name:'Save privately',exact:true}).click();
  await panel.getByText('Saved privately. Timing is estimated; adjust it by ear if needed.',{exact:true}).waitFor();
  const after=await(await page.request.get(fixture.origin+'/api/jams?song=synthetic-alpha')).json();
  assert.equal(after.jams.length,2);const second=after.jams.find(item=>item.id!==jam.id);assert.equal(second.captureEnd,'interrupted');assert.ok(second.alignment.coverage.sourceStart>=2.999,JSON.stringify(second.alignment));
  assert.deepEqual(errors,[]);await context.close();
 } finally {await browser.close();await fixture.close();await rm(dir,{recursive:true,force:true});}
});
